# Generated by Django 3.0.11 on 2020-12-08 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='landline_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile Number', regex='\\d{5}([- ]?)\\d{6}')]),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile Number', regex='^[6-9]\\d{9}')]),
        ),
    ]
