# Generated by Django 3.0.11 on 2020-12-09 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_directory', '0004_auto_20201209_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactviewcount',
            name='date',
        ),
        migrations.AddField(
            model_name='contactviewcount',
            name='count_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
